[package]
name = "redisbrute"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.1.1", features = ["derive"] }
crossbeam-queue = "0.3.8"
parking_lot = "0.12.1"
